export const adminMessages = {
  shell: {
    title: "Ադմին",
    dashboard: "Վահանակ",
    products: "Ապրանքներ",
    brands: "Բրենդներ",
    categories: "Կատեգորիաներ",
    logout: "Դուրս գալ",
  },
  common: {
    save: "Պահպանել",
    saving: "Պահպանում...",
    edit: "Խմբագրել",
    delete: "Ջնջել",
    cancel: "Չեղարկել",
    confirm: "Հաստատում",
    yesDelete: "Այո, ջնջել",
    backToBrands: "Վերադառնալ բրենդներ",
    backToCategories: "Վերադառնալ կատեգորիաներ",
    imageMissing: "Նկար չկա",
    loading: "Բեռնվում է...",
    notSpecified: "Նշված չէ",
  },
  login: {
    eyebrow: "Ադմինի մուտք",
    title: "Մուտք ադմին վահանակ",
    email: "Էլ. փոստ",
    password: "Գաղտնաբառ",
    submit: "Մուտք գործել",
    submitting: "Մուտք...",
    emailError: "Մուտքագրեք email-ը",
    passwordError: "Նվազագույնը 6 նիշ",
    failed: "Չհաջողվեց մուտք գործել։ Ստուգեք backend-ը և ադմինի տվյալները։",
  },
  dashboard: {
    eyebrow: "Ընդհանուր տեսք",
    title: "Վահանակ",
    loadError: "Չհաջողվեց բեռնել վահանակը backend-ից։",
    totalProducts: "Ապրանքներ",
    brands: "Բրենդներ",
    categories: "Կատեգորիաներ",
    newest: "Նորույթներ",
    featured: "Հանրաճանաչ",
    latestProducts: "Վերջին ապրանքները",
  },
  products: {
    title: "Ապրանքներ",
    create: "Ստեղծել ապրանք",
    createTitle: "Ստեղծել ապրանք",
    editTitle: "Խմբագրել ապրանքը",
    loadError: "Չհաջողվեց բեռնել ապրանքները backend-ից։",
    deleteError: "Չհաջողվեց ջնջել ապրանքը backend-ում։",
    tableImage: "Նկար",
    tableName: "Անվանում",
    tableBrand: "Բրենդ",
    tablePrice: "Գին",
    tableActions: "Գործողություններ",
    deleteTitle: "Ջնջե՞լ ապրանքը",
    deleteDescription: (name: string) =>
      `Դուք պատրաստվում եք ջնջել «${name}» ապրանքը։ Այս գործողությունը շարունակե՞լ։`,
    loadFormError: "Չհաջողվեց բեռնել ապրանքի տվյալները backend-ից։",
    loadMetaError: "Չհաջողվեց բեռնել բրենդներն ու կատեգորիաները backend-ից։",
    saveError: "Չհաջողվեց պահպանել։ Ստուգեք backend-ը, JWT-ն և պարտադիր դաշտերը։",
    invalidVariantVolume: "Տարբերակների համար նշեք ծավալը կամ չափը։",
    invalidAccessory:
      "Լրացրեք պարտադիր դաշտերը։ Աքսեսուարի համար նշեք գինը և առնվազն մեկ նկար։",
    invalidProduct:
      "Լրացրեք պարտադիր դաշտերը։ Տարբերակի համար նշեք չափը, գինը և առնվազն մեկ նկար։",
    variantImagesError: "Ավելացրեք առնվազն մեկ նկար",
    variantSectionAccessory: "Ապրանքի տվյալներ",
    variantSectionProduct: "Ապրանքի տարբերակներ",
    variantSectionAccessoryHint: "Աքսեսուարի համար պահվում է մեկ գին և մի քանի նկար։",
    variantSectionProductHint:
      "Սկզբում ավելացվում է մեկ դատարկ տարբերակ։ Եթե պետք լինի, հետո կարող եք ավելացնել ևս տարբերակներ։",
    addVariant: "Ավելացնել տարբերակ",
    addImage: "Ավելացնել նկար",
    deleteVariant: "Ջնջել տարբերակը",
    deleteImage: "Ջնջել նկարը",
    variantPrimary: "Հիմնական տարբերակ",
    variantNumber: (index: number) => `Տարբերակ ${index + 1}`,
    variantHintAccessory: "Նշեք գինը և ավելացրեք նկարներ",
    variantHintProduct: "Օր.` 50ml, 100ml, set",
    imagesForVariant: "Նկարներ այս տարբերակի համար",
    imageLabel: (index: number) => `Նկար ${index + 1}`,
    deleteVariantTitle: "Ջնջե՞լ տարբերակը",
    deleteImageTitle: "Ջնջե՞լ նկարը",
    deleteVariantDescription: (label: string) =>
      `Դուք պատրաստվում եք ջնջել «${label}» տարբերակը։ Շարունակե՞լ։`,
    deleteImageDescription: "Այս նկարը կհեռացվի տարբերակից։ Շարունակե՞լ։",
    nameAm: "Անվանում (AM)",
    nameRu: "Անվանում (RU)",
    nameEn: "Անվանում (EN)",
    descriptionAm: "Նկարագրություն (AM)",
    descriptionRu: "Նկարագրություն (RU)",
    descriptionEn: "Նկարագրություն (EN)",
    brand: "Բրենդ",
    chooseBrand: "Ընտրեք բրենդը",
    category: "Կատեգորիա",
    chooseCategory: "Ընտրեք կատեգորիան",
    gender: "Սեռ",
    country: "Երկիր",
    releaseYear: "Թողարկման տարի",
    fragranceType: "Բույրի տեսակ",
    concentrationAm: "Կոնցենտրացիա (AM)",
    concentrationRu: "Կոնցենտրացիա (RU)",
    concentrationEn: "Կոնցենտրացիա (EN)",
    longevity: "Երկարակեցություն",
    sillage: "Շլեյֆ",
    topNotesAm: "Վերին նոտաներ (AM)",
    topNotesRu: "Վերին նոտաներ (RU)",
    topNotesEn: "Վերին նոտաներ (EN)",
    middleNotesAm: "Միջին նոտաներ (AM)",
    middleNotesRu: "Միջին նոտաներ (RU)",
    middleNotesEn: "Միջին նոտաներ (EN)",
    baseNotesAm: "Բազային նոտաներ (AM)",
    baseNotesRu: "Բազային նոտաներ (RU)",
    baseNotesEn: "Բազային նոտաներ (EN)",
    variantVolume: "Տարբերակ / չափ",
    price: "Գին",
    oldPrice: "Հին գին",
    featured: "Հանրաճանաչ",
    isNew: "Նորույթ",
    active: "Ցուցադրել",
    loadingCurrent: "Սպասեք մի պահ, բեռնում ենք ապրանքի ընթացիկ տվյալները։",
    nameRequired: "Մուտքագրեք ապրանքի անվանումը",
    descriptionRequired: "Գրեք ամբողջական նկարագրություն",
    requiredField: "Պարտադիր դաշտ է",
    nonNegative: "Չի կարող լինել բացասական",
  },
  taxonomy: {
    brandsTitle: "Բրենդներ",
    categoriesTitle: "Կատեգորիաներ",
    createBrand: "Ստեղծել բրենդ",
    createCategory: "Ստեղծել կատեգորիա",
    editBrand: "Խմբագրել բրենդը",
    editCategory: "Խմբագրել կատեգորիան",
    saveChanges: "Պահպանել փոփոխությունները",
    add: "Ավելացնել",
    nameAm: "Անվանում (AM)",
    nameRu: "Անվանում (RU)",
    nameEn: "Անվանում (EN)",
    descriptionAm: "Նկարագրություն (AM)",
    descriptionRu: "Նկարագրություն (RU)",
    descriptionEn: "Նկարագրություն (EN)",
    brandImage: "Բրենդի նկար",
    enterName: "Մուտքագրեք անվանումը։",
    loadBrandsError: "Չհաջողվեց բեռնել բրենդները backend-ից։",
    loadCategoriesError: "Չհաջողվեց բեռնել կատեգորիաները backend-ից։",
    saveError: "Չհաջողվեց պահպանել։ Ստուգեք backend-ը և JWT-ն։",
    deleteError: "Չհաջողվեց ջնջել գրառումը backend-ում։",
    protected: "Պաշտպանված",
    createTitleBrand: "Ստեղծել բրենդ",
    createTitleCategory: "Ստեղծել կատեգորիա",
    emptyBrands: "Բրենդները չեն բեռնվել backend-ից։",
    emptyCategories: "Կատեգորիաները չեն բեռնվել backend-ից։",
    deleteBrandTitle: "Ջնջե՞լ բրենդը",
    deleteCategoryTitle: "Ջնջե՞լ կատեգորիան",
    deleteDescription: (name: string) =>
      `Դուք պատրաստվում եք ջնջել «${name}»-ը։ Այս գործողությունը շարունակե՞լ։`,
  },
} as const;

export type AdminMessages = typeof adminMessages;
