import { Brand, Category, Product } from "@/types/catalog";

export const mockBrands: Brand[] = [
  {
    id: "brand-dior",
    name: "Dior",
    slug: "dior",
    logo: "DI",
    image: "/images/perfume-hero.png",
    description: "Французская классика, узнаваемые композиции и элегантная подача.",
    isActive: true,
  },
  {
    id: "brand-chanel",
    name: "Chanel",
    slug: "chanel",
    logo: "CH",
    image: "/images/perfume-hero.png",
    description: "Лаконичные флаконы, чистая эстетика и культовые ароматы.",
    isActive: true,
  },
  {
    id: "brand-tom-ford",
    name: "Tom Ford",
    slug: "tom-ford",
    logo: "TF",
    image: "/images/perfume-hero.png",
    description: "Глубокие нишевые акценты, специи, кожа и выразительный шлейф.",
    isActive: true,
  },
  {
    id: "brand-byredo",
    name: "Byredo",
    slug: "byredo",
    logo: "BY",
    image: "/images/perfume-hero.png",
    description: "Современные минималистичные ароматы с чистой архитектурой нот.",
    isActive: true,
  },
];

export const mockCategories: Category[] = [
  {
    id: "cat-women",
    name: "Женская парфюмерия",
    slug: "zhenskaya-parfyumeriya",
    description: "Цветочные, сладкие и свежие композиции на каждый день и вечер.",
    image: "/images/perfume-hero.png",
    isActive: true,
  },
  {
    id: "cat-men",
    name: "Мужская парфюмерия",
    slug: "muzhskaya-parfyumeriya",
    description: "Древесные, пряные и цитрусовые ароматы с уверенным характером.",
    image: "/images/perfume-hero.png",
    isActive: true,
  },
  {
    id: "cat-unisex",
    name: "Унисекс",
    slug: "unisex",
    description: "Композиции без границ: свежие, восточные и нишевые сочетания.",
    image: "/images/perfume-hero.png",
    isActive: true,
  },
  {
    id: "cat-niche",
    name: "Нишевая парфюмерия",
    slug: "nishevaya-parfyumeriya",
    description: "Редкие аккорды, высокая концентрация и выразительная история.",
    image: "/images/perfume-hero.png",
    isActive: true,
  },
];

export const mockProducts: Product[] = [
  {
    id: "product-1",
    name: "Rose Signature",
    slug: "rose-signature-100ml",
    brandId: "brand-chanel",
    brand: mockBrands[1],
    categoryId: "cat-women",
    category: mockCategories[0],
    price: 42000,
    oldPrice: 48000,
    volume: "100ml",
    gender: "female",
    fragranceType: "floral",
    description:
      "Нежная цветочная композиция с прозрачным розовым сердцем, чистым мускусом и мягкой древесной базой.",
    shortDescription: "Пудровая роза, чистый мускус и мягкая древесная база.",
    mainImage: "/images/products/perfume-card-4.png",
    galleryImages: ["/images/products/perfume-card-4.png", "/images/products/perfume-card-3.png"],
    isAvailable: true,
    stockStatus: "В наличии",
    isFeatured: true,
    isNew: true,
    isActive: true,
    topNotes: "бергамот, розовый перец",
    middleNotes: "роза, пион, жасмин",
    baseNotes: "мускус, кедр, амбра",
    longevity: "high",
    sillage: "medium",
    concentration: "Eau de Parfum",
    country: "France",
    releaseYear: 2025,
  },
  {
    id: "product-2",
    name: "Noir Wood",
    slug: "noir-wood-50ml",
    brandId: "brand-tom-ford",
    brand: mockBrands[2],
    categoryId: "cat-men",
    category: mockCategories[1],
    price: 56000,
    volume: "50ml",
    gender: "male",
    fragranceType: "woody",
    description:
      "Глубокий древесно-пряный аромат с сухим кедром, табаком и темной амброй.",
    shortDescription: "Кедр, табак и темная амбра для вечернего образа.",
    mainImage: "/images/products/perfume-card-6.png",
    galleryImages: ["/images/products/perfume-card-6.png", "/images/products/perfume-card-5.png"],
    isAvailable: true,
    stockStatus: "В наличии",
    isFeatured: true,
    isNew: false,
    isActive: true,
    topNotes: "кардамон, черный перец",
    middleNotes: "кедр, пачули",
    baseNotes: "табак, амбра, кожа",
    longevity: "very_high",
    sillage: "strong",
    concentration: "Parfum",
    country: "USA",
    releaseYear: 2024,
  },
  {
    id: "product-3",
    name: "Citrus Veil",
    slug: "citrus-veil-75ml",
    brandId: "brand-byredo",
    brand: mockBrands[3],
    categoryId: "cat-unisex",
    category: mockCategories[2],
    price: 39000,
    volume: "75ml",
    gender: "unisex",
    fragranceType: "citrus",
    description:
      "Светлый унисекс аромат с грейпфрутом, зеленым чаем и чистым мускусным финишем.",
    shortDescription: "Грейпфрут, зеленый чай и чистый мускус.",
    mainImage: "/images/products/perfume-card-2.png",
    galleryImages: ["/images/products/perfume-card-2.png", "/images/products/perfume-card-1.png"],
    isAvailable: true,
    stockStatus: "В наличии",
    isFeatured: false,
    isNew: true,
    isActive: true,
    topNotes: "грейпфрут, лимон",
    middleNotes: "зеленый чай, нероли",
    baseNotes: "мускус, ветивер",
    longevity: "medium",
    sillage: "soft",
    concentration: "Eau de Toilette",
    country: "Sweden",
    releaseYear: 2026,
  },
  {
    id: "product-4",
    name: "Amber Bloom",
    slug: "amber-bloom-100ml",
    brandId: "brand-dior",
    brand: mockBrands[0],
    categoryId: "cat-niche",
    category: mockCategories[3],
    price: 61000,
    volume: "100ml",
    gender: "unisex",
    fragranceType: "oriental",
    description:
      "Теплая восточная композиция с амброй, ванилью, шафраном и бархатным цветочным аккордом.",
    shortDescription: "Амбра, ваниль, шафран и бархатный цветочный аккорд.",
    mainImage: "/images/products/perfume-card-5.png",
    galleryImages: ["/images/products/perfume-card-5.png", "/images/products/perfume-card-4.png"],
    isAvailable: false,
    stockStatus: "Нет в наличии",
    isFeatured: true,
    isNew: false,
    isActive: true,
    topNotes: "шафран, мандарин",
    middleNotes: "жасмин, ирис",
    baseNotes: "амбра, ваниль, сандал",
    longevity: "very_high",
    sillage: "very_strong",
    concentration: "Eau de Parfum",
    country: "France",
    releaseYear: 2023,
  },
];
